version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: "fix(deps)"
      prefix-development: 'chore(deps):'
    groups:
      actions:
        patterns:
          - "@actions/*"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "prettier"
      jest:
        patterns:
          - "jest"
          - "jest-*"
          - "ts-jest"
          - "@types/jest"
