name: 'Setup Chrome'
description: 'Install and setup Google Chrome and Chromium'
author: "Shin'ya Ueoka"
inputs:
  chrome-version:
    description: |-
      The Google Chrome/Chromium version to install and use.
    default: latest
    required: false
  install-dependencies:
    description: |-
      Install dependent packages for Google Chrome/Chromium (Linux only).
    default: false
  no-install-chromedriver:
    description: |-
      Install only Google Chrome/Chromium browser and skip installing chromedriver
    default: false
  no-sudo:
    description: |-
      Do not use sudo to install Google Chrome/Chromium (Linux only).
    default: false
outputs:
  chrome-version:
    description: 'The installed Google Chrome/Chromium version. Useful when given a latest version.'
  chrome-path:
    description: 'The installed Google Chrome/Chromium path.'
  chromedriver-version:
    description: 'The installed ChromeDriver version. Useful when given a latest version.'
  chromedriver-path:
    description: 'The installed ChromeDriver path.'
runs:
  using: 'node20'
  main: 'index.js'
