name: 'Setup Chrome'
description: 'Install and setup Google Chrome and Chromium'
author: "Shin'ya Ueoka"
inputs:
  chrome-version:
    description: |-
      The Google Chrome/Chromium version to install and use.
    default: latest
    required: false
outputs:
  chrome-version:
    description: 'The installed Google Chrome/Chromium version. Useful when given a latest version.'
  chrome-path:
    description: 'The installed Google Chrome/Chromium path.'
runs:
  using: 'node16'
  main: 'index.js'
