name: 'build-test'
on:
  push:
    branches-ignore:
      - master
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - run: pnpm package
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: ./dist/

  test:
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ["", 1295939, 120, dev, latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist

      - name: Install Google Chrome
        uses: ./
        with:
          chrome-version: ${{ matrix.version }}
          install-chromedriver: true
        id: setup-chrome
      - if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          "${{ steps.setup-chrome.outputs.chrome-path }}" --version
          "${{ steps.setup-chrome.outputs.chromedriver-path }}" --version
      - if: runner.os == 'Windows'
        run: |
          (Get-Item (Get-Command "${{ steps.setup-chrome.outputs.chrome-path }}").Source).VersionInfo.ProductVersion
          (Get-Item (Get-Command "${{ steps.setup-chrome.outputs.chromedriver-path }}").Source).VersionInfo.ProductVersion

  test-windows-arm:
    needs: [build]
    runs-on: windows-11-arm
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist
      - name: Install Google Chrome
        uses: ./
        with:
          chrome-version: 1485971
          install-chromedriver: true
        id: setup-chrome
      - run: |
          (Get-Item (Get-Command "${{ steps.setup-chrome.outputs.chrome-path }}").Source).VersionInfo.ProductVersion
          (Get-Item (Get-Command "${{ steps.setup-chrome.outputs.chromedriver-path }}").Source).VersionInfo.ProductVersion

  test-linux-arm:
    needs: [build]
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist
      - name: Install Google Chrome
        uses: ./
        with:
          chrome-version: canary
          install-chromedriver: true
        id: setup-chrome
      - run: |
          "${{ steps.setup-chrome.outputs.chrome-path }}" --version
          "${{ steps.setup-chrome.outputs.chromedriver-path }}" --version

  test-install-dependencies:
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        container:
          - ""
          - fedora
          - opensuse/leap
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist
      - name: Install action dependencies
        run: apt-get update && apt-get install -y unzip
        if: ${{ matrix.container == 'debian' || matrix.container == 'ubuntu' || matrix.container == 'linuxmintd/mint21-amd64' }}
      - name: Install action dependencies
        run: yum install --assumeyes unzip
        if: ${{ matrix.container == 'redhat/ubi9' || matrix.container == 'oraclelinux:9' || matrix.container == 'fedora' }}
      - name: Install action dependencies
        run: zypper install --no-confirm unzip
        if: ${{ matrix.container == 'opensuse/leap' || matrix.container == 'registry.suse.com/bci/bci-base:15.5' }}

      # Override GITHUB_PATH by the current PATH to prevent the issue discussed in https://github.com/actions/runner/issues/3210
      - run: echo "$PATH" >>"$GITHUB_PATH"
        if: ${{ matrix.container == 'opensuse/leap' || matrix.container == 'registry.suse.com/bci/bci-base:15.5' }}

      - name: Install Google Chrome
        uses: ./
        with:
          chrome-version: 120
          install-chromedriver: true
          install-dependencies: true
        id: setup-chrome
      - run: |
          "${{ steps.setup-chrome.outputs.chrome-path }}" --version
          "${{ steps.setup-chrome.outputs.chromedriver-path }}" --version
